name: Nations
main: com.github.Dagrond.NationPlugin
version: 0.1
softdepend: [AdminTools, Multiverse-Core]
depend: [WorldGuard, Vault]
commands:
   Nation:
      aliases: [n]
      description: Komenda panstw.
      usage: /n