name: Nations
main: com.gmail.ZiomuuSs.NationPlugin
version: 0.1
softdepend: [AdminTools, Multiverse-Core]
depend: [WorldGuard]
commands:
   Nation:
      aliases: [n]
      description: Komenda panstw.
      usage: /n